<form action="<?php echo $block->getFormAction() ?>" method="post">
  <label for="first_name">First name:</label>
  <input type="text" id="first_name" name="first_name" ><br><br>
  <label for="last_name">Last name:</label>
  <input type="text" id="last_name" name="last_name" ><br><br>
  <label for="email">Email:</label>
  <input type="text" id="email" name="email" ><br><br>
  <label for="phone_number">Phone Number:</label>
  <input type="text" id="phone_number" name="phone_number" ><br><br>
  <label for="mesage">Message:</label>
  <input type="text" id="message" name="message"><br><br>
  <input type="submit" value="Submit">
</form>